TARGET := svd

LDFLAGS := -lm

SOURCES := $(wildcard common/*.c) $(wildcard includes/*.c) $(wildcard *.c)

RUNARGS := small.txt result/result_U.txt 

CLEANMETOO := result/result_U.txt

ACCEPT_DIR := ../../../repos/accept
include $(ACCEPT_DIR)/accept.mk

