TARGET := svd
LDFLAGS := -lm 

SOURCES := $(wildcard common/*.c) $(wildcard *.c) $(wildcard includes/*.c)

RUNARGS := small.txt results/result_U.txt results/result_V.txt

ACCEPT_DIR := ../../accept
include $(ACCEPT_DIR)/accept.mk

