TARGET := srr

CFLAGS := -02
LD FLAGS := -lm

SOURCES := App.c BmpHandler.c Motion Estimation.c SRREngine.c SystemMatrices.c

RUNARGS := 

ACCEPT_DIR := ../../accept
include $(ACCEPT_DIR)/accept.mk