TARGET := rbm

LDFLAGS := -lm 

CFLAGS := -DUSERS=10 -DTEST_USERS=10 -DMOVIES=10 -DLOOPS=20 

SOURCES := includes/photonTiming.c main.c twister.c 

RUNARGS := out.txt

ACCEPT_DIR := ../../accept
include $(ACCEPT_DIR)/accept.mk