TARGET := pca

LDFLAGS := -lm

CFLAGS := 

SOURCES := pca.c includes/photonTiming.c

RUNARGS := small.data 1593 256 R output.txt

ACCEPT_DIR := ../../../repos/accept
include $(ACCEPT_DIR)/accept.mk
